Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cfg.initialize()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [43mcfg[49m[38;5;241;43m.[39;49m[43minitialize[49m[43m([49m[43m)[49m

File [0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/oggm/cfg.py:638[0m, in [0;36minitialize[0;34m(file, logging_level, params, future)[0m
[1;32m    636[0m [38;5;66;03m# Make sure we have a proper cache dir[39;00m
[1;32m    637[0m [38;5;28;01mfrom[39;00m [38;5;21;01moggm[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m [38;5;28;01mimport[39;00m download_oggm_files, get_demo_file
[0;32m--> 638[0m [43mdownload_oggm_files[49m[43m([49m[43m)[49m
[1;32m    640[0m [38;5;66;03m# Read in the demo glaciers[39;00m
[1;32m    641[0m file [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(os[38;5;241m.[39mpath[38;5;241m.[39mabspath(os[38;5;241m.[39mpath[38;5;241m.[39mdirname([38;5;18m__file__[39m)),
[1;32m    642[0m                     [38;5;124m'[39m[38;5;124mdata[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mdemo_glaciers.csv[39m[38;5;124m'[39m)

File [0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/oggm/utils/_downloads.py:834[0m, in [0;36mdownload_oggm_files[0;34m()[0m
[1;32m    832[0m [38;5;28;01mdef[39;00m [38;5;21mdownload_oggm_files[39m():
[1;32m    833[0m     [38;5;28;01mwith[39;00m get_lock():
[0;32m--> 834[0m         [38;5;28;01mreturn[39;00m [43m_download_oggm_files_unlocked[49m[43m([49m[43m)[49m

File [0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/oggm/utils/_downloads.py:849[0m, in [0;36m_download_oggm_files_unlocked[0;34m()[0m
[1;32m    847[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m os[38;5;241m.[39mpath[38;5;241m.[39mexists(sdir):
[1;32m    848[0m     ofile [38;5;241m=[39m file_downloader(zip_url)
[0;32m--> 849[0m     [38;5;28;01mwith[39;00m [43mzipfile[49m[38;5;241;43m.[39;49m[43mZipFile[49m[43m([49m[43mofile[49m[43m)[49m [38;5;28;01mas[39;00m zf:
[1;32m    850[0m         zf[38;5;241m.[39mextractall(odir)
[1;32m    851[0m     [38;5;28;01massert[39;00m os[38;5;241m.[39mpath[38;5;241m.[39misdir(sdir)

File [0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/zipfile.py:1257[0m, in [0;36mZipFile.__init__[0;34m(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)[0m
[1;32m   1255[0m [38;5;28;01mtry[39;00m:
[1;32m   1256[0m     [38;5;28;01mif[39;00m mode [38;5;241m==[39m [38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m:
[0;32m-> 1257[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_RealGetContents[49m[43m([49m[43m)[49m
[1;32m   1258[0m     [38;5;28;01melif[39;00m mode [38;5;129;01min[39;00m ([38;5;124m'[39m[38;5;124mw[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m):
[1;32m   1259[0m         [38;5;66;03m# set the modified flag so central directory gets written[39;00m
[1;32m   1260[0m         [38;5;66;03m# even if no files are added to the archive[39;00m
[1;32m   1261[0m         [38;5;28mself[39m[38;5;241m.[39m_didModify [38;5;241m=[39m [38;5;28;01mTrue[39;00m

File [0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/zipfile.py:1320[0m, in [0;36mZipFile._RealGetContents[0;34m(self)[0m
[1;32m   1318[0m fp [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mfp
[1;32m   1319[0m [38;5;28;01mtry[39;00m:
[0;32m-> 1320[0m     endrec [38;5;241m=[39m [43m_EndRecData[49m[43m([49m[43mfp[49m[43m)[49m
[1;32m   1321[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m:
[1;32m   1322[0m     [38;5;28;01mraise[39;00m BadZipFile([38;5;124m"[39m[38;5;124mFile is not a zip file[39m[38;5;124m"[39m)

File [0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/zipfile.py:263[0m, in [0;36m_EndRecData[0;34m(fpin)[0m
[1;32m    257[0m [38;5;124;03m"""Return data from the "End of Central Directory" record, or None.[39;00m
[1;32m    258[0m 
[1;32m    259[0m [38;5;124;03mThe data is a list of the nine items in the ZIP "End of central dir"[39;00m
[1;32m    260[0m [38;5;124;03mrecord followed by a tenth item, the file seek offset of this record."""[39;00m
[1;32m    262[0m [38;5;66;03m# Determine file size[39;00m
[0;32m--> 263[0m [43mfpin[49m[38;5;241;43m.[39;49m[43mseek[49m([38;5;241m0[39m, [38;5;241m2[39m)
[1;32m    264[0m filesize [38;5;241m=[39m fpin[38;5;241m.[39mtell()
[1;32m    266[0m [38;5;66;03m# Check to see if this is ZIP file with no archive comment (the[39;00m
[1;32m    267[0m [38;5;66;03m# "end of central directory" structure should be the last item in the[39;00m
[1;32m    268[0m [38;5;66;03m# file if this is the case).[39;00m

[0;31mAttributeError[0m: 'NoneType' object has no attribute 'seek'
AttributeError: 'NoneType' object has no attribute 'seek'

